/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "forwarder_pb.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Packet, Packet, AUTO)


PB_BIND(CanFrame, CanFrame, AUTO)



