/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_EXAMPLES_SIMPLE_FORWARDER_PB_PB_H_INCLUDED
#define PB_EXAMPLES_SIMPLE_FORWARDER_PB_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Packet {
    pb_callback_t canFrames;
} Packet;

typedef struct _CanFrame {
    uint32_t can_id;
    uint64_t timestamp;
    pb_byte_t can_data[8];
    uint32_t can_bus;
} CanFrame;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Packet_init_default                      {{{NULL}, NULL}}
#define CanFrame_init_default                    {0, 0, {0}, 4}
#define Packet_init_zero                         {{{NULL}, NULL}}
#define CanFrame_init_zero                       {0, 0, {0}, 4}

/* Field tags (for use in manual encoding/decoding) */
#define CanFrame_can_id_tag                       1
#define CanFrame_timestamp_tag                    2
#define CanFrame_can_data_tag                     3
#define CanFrame_can_bus_tag                      4
#define Packet_canFrames_tag                     1

/* Struct field encoding specification for nanopb */
#define Packet_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  canFrames,         1)
#define Packet_CALLBACK pb_default_field_callback
#define Packet_DEFAULT NULL
#define Packet_canFrames_MSGTYPE CanFrame

#define CanFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   can_id,            1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, can_data,          3) \
X(a, STATIC,   SINGULAR, UINT32,   can_bus,         4)
#define CanFrame_CALLBACK NULL
#define CanFrame_DEFAULT NULL

extern const pb_msgdesc_t Packet_msg;
extern const pb_msgdesc_t CanFrame_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Packet_fields &Packet_msg
#define CanFrame_fields &CanFrame_msg

/* Maximum encoded size of messages (where known) */
/* Packet_size depends on runtime parameters */
#define CanFrame_size                            128
#define EXAMPLES_SIMPLE_FORWARDER_PB_PB_H_MAX_SIZE CanFrame_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
